test:
  mode: anomaly_detection
  img_size: 224
  num_classes: 6

paths:
  root: '/home/tanaka/demo_data'
  model: 'trained_models/multilabel_cross_valid_6class_fold4/model_best.pth'
  save_name: 'cross_valid_6class_fold4_results'
