test:
  mode: anomaly_detection
  img_size: 224
  num_classes: 15

paths:
  root: '/home/tanaka/demo_data'
  save_dir: '/home/tanaka/labeling/15class_1'
  model: '/home/tanaka/labeling/models/multilabel_cross_valid_15class_fold1/model_best.pth'
